package main

var ioob string "Fatal: Index Out Of Bounds: index[\0"
var ioob2 string "] for object with length: \0"
var ioob3 string "\n\0"

function start
	call main
	mov rdi rax
	mov rax 0x3C
	syscall

function index_oob
	prologue
	push rsi
	push rdi
	
	
	lea rdi ioob
	call puts

	pop rdi
	call puti

	lea rdi ioob2
	call puts

	pop rdi
	call puti

	lea rdi ioob3
	call puts

	mov rdi 1
	mov rax 0x3C
	syscall

	epilogue